iOS 에서 BFCache 동작할 때, iframe 내 이벤트가 비정상적으로 발생하는 문제 처리 정리
teamdable/techblog pull request #21
Opened 2019-10-07 04:46 UTC by bangchangbae

얼마전 ios 에서만 발생한 문제를 처리한 것을 정리해 보았습니다.

2019-10-10 00:59 UTC, goonookim requested changes
👍👍

2019-10-10 00:59 UTC, goonookim commented on _posts/2019-10-07-iframe-event-issue-with-bfcache.md
> +안녕하세요. 방창배입니다..
dot은 하나인 편이 좋지 않을까요? ㅎㅎ

2019-10-10 00:59 UTC, goonookim commented on _posts/2019-10-07-iframe-event-issue-with-bfcache.md
> +# 발생 원인 요약
h1을 의미하신건가요? "iPhone에서 클릭이 안 된다." 절의 sub라면 h3(`###`)이 어떨까 합니다.

2019-10-10 00:59 UTC, goonookim commented on _posts/2019-10-07-iframe-event-issue-with-bfcache.md
> +# 발생 원인 요약
그리고 블로그에서 h1이 h2보다도 작게 보이는 이슈가 있더라고요. 가급적 h2부터 사용해주시기를 권장드립니다.

2019-10-10 00:59 UTC, goonookim commented on _posts/2019-10-07-iframe-event-issue-with-bfcache.md
> +이 이슈는 평상시에는 재현되지 않습니다. 또한 iOS가 아니면 재현되지 않습니다. iOS에서도 항상 발생하는 것은 아니며 **BFCache**(Back-Forwrad Cache)를 사용할 때 문제가 발생합니다.
```suggestion
이 이슈는 평상시에는 재현되지 않습니다. 또한 iOS가 아니면 재현되지 않습니다. iOS에서도 항상 발생하는 것은 아니며 **BFCache**(Back-Forward Cache)를 사용할 때 문제가 발생합니다.
```

Forwrad <- typo입니다.

2019-10-10 00:59 UTC, goonookim commented on _posts/2019-10-07-iframe-event-issue-with-bfcache.md
> +자식 페이지에서 `link` *element* 를 제거하면 이슈가 재현되지 않습니다. 위 샘플에서 보는 것과 같이 `link` *element* 에서 sytle sheet를 로드하지 못해도 `ifame` 내에 클릭 이벤트가 발생하지 않습니다.
```suggestion
자식 페이지에서 `link` *element* 를 제거하면 이슈가 재현되지 않습니다. 위 샘플에서 보는 것과 같이 `link` *element* 에서 style sheet를 로드하지 못해도 `iframe` 내에 클릭 이벤트가 발생하지 않습니다.
```

여기도 영문 타이포

2019-10-10 00:59 UTC, goonookim commented on _posts/2019-10-07-iframe-event-issue-with-bfcache.md
> +[https://bang-express-example.herokuapp.com/iframe-sample/](https://bang-express-example.herokuapp.com/iframe-sample/)
예제 페이지는 개인 사이트 대신 jsbin 같은 무료로 활용할 수 있는 외부 서비스를 쓰면 좋겠습니다.

2019-10-10 00:59 UTC, goonookim commented on _posts/2019-10-07-iframe-event-issue-with-bfcache.md
> +구현에 대한 사항은 [NAVER D2](https://d2.naver.com/helloworld/80243)를 참조하였습니다.
네이버 D2글은 글 제목이 포함되면 좋겠습니다.

예를 들어,

```suggestion
구현에 대한 사항은 [NAVER D2: 터치 이벤트를 이용한 사용자 제스처 분석](https://d2.naver.com/helloworld/80243)를 참조하였습니다.
```

2019-10-10 00:59 UTC, goonookim commented on _posts/2019-10-07-iframe-event-issue-with-bfcache.md
> +간단하게 생각해 보면 `touchmove`를 감지하여 같은 자리에서 `touchestart`와 `toucheend`가 발생하였는지 확인할 수 있습니다. 이를 기반으로 `click`을 발생시킬 수 있습니다. 더욱 안전한 동작을 위해서 바로 `click`을 보내지 않고, 중간 이벤트를 만들어서 최대한 `click` 이 올라오는지 확인한 후 `click` 이
touchestart, toucheend typo입니다.

```suggestion
간단하게 생각해 보면 `touchmove`를 감지하여 같은 자리에서 `touchstart`와 `touchend`가 발생하였는지 확인할 수 있습니다. 이를 기반으로 `click`을 발생시킬 수 있습니다. 더욱 안전한 동작을 위해서 바로 `click`을 보내지 않고, 중간 이벤트를 만들어서 최대한 `click` 이 올라오는지 확인한 후 `click` 이 중간에 오면 `click` 이벤트 발생을 취소하고 이벤트가 발생하지 않는다면 구현을 통해서 이벤트를 발생시키도록 하였습니다.
```

2019-10-10 00:59 UTC, goonookim commented on _posts/2019-10-07-iframe-event-issue-with-bfcache.md
> +          let _lazyCilckTimer_ = undefined;
```suggestion
          let _lazyClickTimer_ = undefined;
```

2019-10-10 00:59 UTC, goonookim commented on _posts/2019-10-07-iframe-event-issue-with-bfcache.md
> +데이블에서는 `iframe` 을 사용하여 위짓을 만들고 있습니다. 데이블에서 사용하는 위짓 스크립트를 사용하여 이어 설명하려고 합니다.
표준어는 "위짓"이지만 데이블에서 공통적으로 사용되는 "위젯"으로 호칭을 통일하는 게 어떨까요?

2019-10-10 00:59 UTC, goonookim commented on _posts/2019-10-07-iframe-event-issue-with-bfcache.md
> +    push: (params) ->
갑자기 coffee가 ㅋㅋ
일일히 JS로 converting 하기는 불편하니 coffeescript라는 언급 정도를 추가하면 좋겠습니다.

2019-10-10 00:59 UTC, goonookim commented on _posts/2019-10-07-iframe-event-issue-with-bfcache.md
> +      dable('renderWidget', 'dablewidget_6XgaZL7N');
공백수의 차이를 없애는 게 좋을 것 같습니다.

2019-10-10 00:59 UTC, goonookim commented on _posts/2019-10-07-iframe-event-issue-with-bfcache.md
> +아름답지는 않지만, 해결은 됩니다. 하지만 다른 고민을 더 해보려고 합니다.
이 방법의 부작용도 언급이 되면 좋을 것 같습니다.

예를 들어, 다른 개발자가 click 이벤트 핸들러를 추가하는 로직을 넣어둔 경우 해당 로직이 제대로 안돈다던지...

2019-10-10 03:19 UTC, sungcheol-kim commented
iOS 버그로 고생 하셨군요;; 좋은 내용 공유해 주셔서 감사합니다 👍 🙇

2019-10-10 03:21 UTC, sungcheol-kim commented on _posts/2019-10-07-iframe-event-issue-with-bfcache.md
> +하지만 궁금함을 뒤로하고 사용자의 불편한 없이 문제를 해결하는 방안을 고민해 보았습니다. 물론 버그로 볼 수 있지만, 현재의 동작하지 않는 문제를 그냥 두고만 볼 수 없는 까닭일듯합니다. 비록 버그성 동작이지만 BFCache 상에서 `click` 에 대한 문제가 있는 다른 개발자들에게 도움이 되길 바라며 내용을 정리해보았습니다.
`불편한 -> 불편함` 수정 요청드립니다 :)

2019-10-10 16:44 UTC, bangchangbae commented on _posts/2019-10-07-iframe-event-issue-with-bfcache.md
> +안녕하세요. 방창배입니다..
불필요한 마침표를 제거하였습니다.

2019-10-10 16:44 UTC, bangchangbae commented on _posts/2019-10-07-iframe-event-issue-with-bfcache.md
> +# 발생 원인 요약
h3 로 사용해야 하는 것을 잘못 표기 하였습니다. 수정하여 반영 하였습니다.

2019-10-10 16:44 UTC, bangchangbae commented on _posts/2019-10-07-iframe-event-issue-with-bfcache.md
> +이 이슈는 평상시에는 재현되지 않습니다. 또한 iOS가 아니면 재현되지 않습니다. iOS에서도 항상 발생하는 것은 아니며 **BFCache**(Back-Forwrad Cache)를 사용할 때 문제가 발생합니다.
오타 수정하였습니다.

2019-10-10 16:46 UTC, bangchangbae commented on _posts/2019-10-07-iframe-event-issue-with-bfcache.md
> +[https://bang-express-example.herokuapp.com/iframe-sample/](https://bang-express-example.herokuapp.com/iframe-sample/)
우선 script 에 대한 코드를 jsfiddle 로 올려 놓았습니다.

다만 이번 예제는 iframe 에 대한 처리여서, 중첩되도록 html 을 구성해야 하는 애로 사항이 있습니다..

현재 만든 page 의 결과만을 url 로 줄 수 있는 서비스가 있을까요?

(원래 jsfiddle 이 훅을 하면 가능했었는데 요새 빠진 것 같습니다..ㅠ)

2019-10-10 16:48 UTC, bangchangbae commented on _posts/2019-10-07-iframe-event-issue-with-bfcache.md
> +구현에 대한 사항은 [NAVER D2](https://d2.naver.com/helloworld/80243)를 참조하였습니다.
반영하였습니다.

2019-10-10 16:49 UTC, bangchangbae commented on _posts/2019-10-07-iframe-event-issue-with-bfcache.md
> +          let _lazyCilckTimer_ = undefined;
오타 수정 하였습니다.

2019-10-10 16:49 UTC, bangchangbae commented on _posts/2019-10-07-iframe-event-issue-with-bfcache.md
> +    push: (params) ->
javascript 로 통일 하였습니다.

2019-10-10 16:50 UTC, bangchangbae commented on _posts/2019-10-07-iframe-event-issue-with-bfcache.md
> +아름답지는 않지만, 해결은 됩니다. 하지만 다른 고민을 더 해보려고 합니다.
원래 지원되는 것을 위에서 억지로 맞추는 것에는 한계가 있다는 것을 언급하는 방향으로 보강하였습니다.

2019-10-10 16:50 UTC, bangchangbae commented on _posts/2019-10-07-iframe-event-issue-with-bfcache.md
> +하지만 궁금함을 뒤로하고 사용자의 불편한 없이 문제를 해결하는 방안을 고민해 보았습니다. 물론 버그로 볼 수 있지만, 현재의 동작하지 않는 문제를 그냥 두고만 볼 수 없는 까닭일듯합니다. 비록 버그성 동작이지만 BFCache 상에서 `click` 에 대한 문제가 있는 다른 개발자들에게 도움이 되길 바라며 내용을 정리해보았습니다.
오기 수정하였습니다.
감사합니다.

2019-10-10 16:51 UTC, bangchangbae commented on _posts/2019-10-07-iframe-event-issue-with-bfcache.md
> +자식 페이지에서 `link` *element* 를 제거하면 이슈가 재현되지 않습니다. 위 샘플에서 보는 것과 같이 `link` *element* 에서 sytle sheet를 로드하지 못해도 `ifame` 내에 클릭 이벤트가 발생하지 않습니다.
오타 수정하였습니다.

2019-10-10 16:51 UTC, bangchangbae commented on _posts/2019-10-07-iframe-event-issue-with-bfcache.md
> +간단하게 생각해 보면 `touchmove`를 감지하여 같은 자리에서 `touchestart`와 `toucheend`가 발생하였는지 확인할 수 있습니다. 이를 기반으로 `click`을 발생시킬 수 있습니다. 더욱 안전한 동작을 위해서 바로 `click`을 보내지 않고, 중간 이벤트를 만들어서 최대한 `click` 이 올라오는지 확인한 후 `click` 이
오타 수정하였습니다.

2019-10-10 16:52 UTC, bangchangbae commented on _posts/2019-10-07-iframe-event-issue-with-bfcache.md
> +      dable('renderWidget', 'dablewidget_6XgaZL7N');
공백 없이 시작하도록 모든 코드를 통일하였습니다.

2019-10-10 16:58 UTC, bangchangbae commented on _posts/2019-10-07-iframe-event-issue-with-bfcache.md
> +데이블에서는 `iframe` 을 사용하여 위짓을 만들고 있습니다. 데이블에서 사용하는 위짓 스크립트를 사용하여 이어 설명하려고 합니다.
맞춤법 검사를 돌리면서 수정하게 되었었습니다.
편하게 볼 수 있도록 위젯으로 변경하였습니다.

2019-10-11 00:38 UTC, sungcheol-kim commented on _posts/2019-10-07-iframe-event-issue-with-bfcache.md
> +하지만 궁금함을 뒤로하고 사용자의 불편한 없이 문제를 해결하는 방안을 고민해 보았습니다. 물론 버그로 볼 수 있지만, 현재의 동작하지 않는 문제를 그냥 두고만 볼 수 없는 까닭일듯합니다. 비록 버그성 동작이지만 BFCache 상에서 `click` 에 대한 문제가 있는 다른 개발자들에게 도움이 되길 바라며 내용을 정리해보았습니다.
🙇

2019-10-15 07:16 UTC, goonookim commented on _posts/2019-10-07-iframe-event-issue-with-bfcache.md
> +[https://bang-express-example.herokuapp.com/iframe-sample/](https://bang-express-example.herokuapp.com/iframe-sample/)
github의 static page 기능(gh-pages)을 써보면 어떨까요?

2019-10-15 08:54 UTC, goonookim commented on _posts/2019-10-07-iframe-event-issue-with-bfcache.md
> +[https://bang-express-example.herokuapp.com/iframe-sample/](https://bang-express-example.herokuapp.com/iframe-sample/)
아니면 본 repo(techblog) 최상단에 directory를 하나 만들면 어떨까요?
예를 들어 "examples"

2019-10-16 08:12 UTC, sunghyunl22 commented on _posts/2019-10-07-iframe-event-issue-with-bfcache.md
> +이 경우 개발자가 `click` 이벤트 조건을 판단해야 합니다. 플랫폼 환경에 따라 `click` 판정이 달라진다고 가정을 해보면 머리가 지끈지끈해줄 수 있습니다. 이번 경우에야 `touchmove`가 없는 것을 `click`으로 판단하였지만 만약 어느 정도 이동을 허용하는 플랫폼이 있다고 가정하면 개발자는 다양한 플랫폼을 하나의 코드에서 처리하고 관리해
지끈지끈해`줄` typo 있습니다 ㅎㅎ

2019-10-16 10:20 UTC, bangchangbae commented on _posts/2019-10-07-iframe-event-issue-with-bfcache.md
> +[https://bang-express-example.herokuapp.com/iframe-sample/](https://bang-express-example.herokuapp.com/iframe-sample/)
내부 static page 를 만드는 방향으로 처리를 해보겠습니다.
의견 주셔서 감사합니다.

2019-10-16 10:58 UTC, bangchangbae commented on _posts/2019-10-07-iframe-event-issue-with-bfcache.md
> +이 경우 개발자가 `click` 이벤트 조건을 판단해야 합니다. 플랫폼 환경에 따라 `click` 판정이 달라진다고 가정을 해보면 머리가 지끈지끈해줄 수 있습니다. 이번 경우에야 `touchmove`가 없는 것을 `click`으로 판단하였지만 만약 어느 정도 이동을 허용하는 플랫폼이 있다고 가정하면 개발자는 다양한 플랫폼을 하나의 코드에서 처리하고 관리해
리뷰 감사합니다!

2019-10-18 12:09 UTC, Jongman-Seo commented on _posts/2019-10-07-iframe-event-issue-with-bfcache.md
> +  const triggingEventName = "click";      // Allow to be Customized
전체 내용과 큰 관련은 없지만 trigging을 찾아봐도 긴가민가하여 혹시 triggering의 오타인지 여쭈어봅니다.

2019-10-18 12:13 UTC, Jongman-Seo commented on _posts/2019-10-07-iframe-event-issue-with-bfcache.md
> +  dable('setService', 'm.ytn.co.kr');
요런거 익명화하면 좋지 않을까합니다 ㅎㅎ

2019-10-20 07:32 UTC, bangchangbae commented on _posts/2019-10-07-iframe-event-issue-with-bfcache.md
> +  const triggingEventName = "click";      // Allow to be Customized
의견 주신 대로 triggering 으로 수정하는 것이 좋을 것 같아 반영 하였습니다.

2019-10-20 07:33 UTC, bangchangbae commented on _posts/2019-10-07-iframe-event-issue-with-bfcache.md
> +  dable('setService', 'm.ytn.co.kr');
고객사 이름을 삭제 하였습니다.

2019-10-20 15:17 UTC, bangchangbae commented on _posts/2019-10-07-iframe-event-issue-with-bfcache.md
> +[https://bang-express-example.herokuapp.com/iframe-sample/](https://bang-express-example.herokuapp.com/iframe-sample/)
내부에 example 로 경로를 만들어서 샘플 코드를 담았습니다.

2019-10-20 15:18 UTC, bangchangbae commented on _posts/2019-10-07-iframe-event-issue-with-bfcache.md
> +  dable('setService', 'm.ytn.co.kr');
표준 위젯으로 코드와 설명을 변경하여 업데이트 하였습니다.

2019-10-21 03:59 UTC, Jongman-Seo commented
@goonookim requested changes 에 남은 부분이 있는지 여쭤봅니다.

2019-10-21 05:28 UTC, goonookim commented on _posts/2019-10-07-iframe-event-issue-with-bfcache.md
>  자식 페이지에서 `link` *element* 를 제거하면 이슈가 재현되지 않습니다. 위 샘플에서 보는 것과 같이 `link` *element* 에서 style sheet를 로드하지 못해도 `ifame` 내에 클릭 이벤트가 발생하지 않습니다.
`ifame` => `iframe` typo입니다.

2019-10-22 10:01 UTC, bangchangbae commented on _posts/2019-10-07-iframe-event-issue-with-bfcache.md
>  자식 페이지에서 `link` *element* 를 제거하면 이슈가 재현되지 않습니다. 위 샘플에서 보는 것과 같이 `link` *element* 에서 style sheet를 로드하지 못해도 `ifame` 내에 클릭 이벤트가 발생하지 않습니다.
오타 수정하였습니다.
리뷰해주셔서 감사합니다.

2019-10-22 10:01 UTC, bangchangbae commented
오타 수정하였습니다.

2019-10-23 08:21 UTC, goonookim approved these changes
고생 많으셨습니다!

2019-10-23 09:03 UTC, seungjae-lee approved these changes

2019-10-23 14:36 UTC, merged

2019-10-23 14:56 UTC, lee-heejin reviewed
@bangchangbae 제목에 `iframe`이 오타가 난 것 같습니다

2019-10-23 14:59 UTC, bangchangbae commented
감사합니다ㅠ